# This file was generated by GoReleaser. DO NOT EDIT.
cask "caura" do
  version "0.10.4"

  on_macos do
    on_arm do
      sha256 "26a1642ed5f7b23979d879f3f6f4d22d2fff6ee5e16596096374beaa2428b009"
      url "https://caura.ai/caura/v#{version}/memclaw_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d92eab74705ac3bd81362ec166ca76522dcf75941351a27e9caccf2976d2d66c"
      url "https://caura.ai/caura/v#{version}/memclaw_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dad45bfc38d1a6bbf6896ce06fa6516ecdfbbe139222de52caa049d8c0c8dd03"
      url "https://caura.ai/caura/v#{version}/memclaw_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b4928f10f3ce5a97d14c51b9a0dfdf85a8f79b878570e37c25f2df9a52f4225b"
      url "https://caura.ai/caura/v#{version}/memclaw_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "caura"
  desc "Local memory broker for AI coding agents"
  homepage "https://caura.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "caura"
  binary "memclaw"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/caura"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/memclaw"] # legacy-name-floor: the staged binary Gatekeeper must unquarantine
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Caura is installed as `caura`. One command wires your agents,
    signs you in, and starts the daemon. The original command name
    remains available too:

      caura setup

    Privacy: by default the broker runs in personal mode. See
    https://caura.ai/legal/privacy for an itemized list of what data
    does and does not leave your machine.
  EOS
end
