# This file was generated by GoReleaser. DO NOT EDIT.
cask "caura" do
  version "0.10.5"

  on_macos do
    on_arm do
      sha256 "a2105e67b8cca1c8f010f277da3c7ec81ff13a012b021a61a820dcfe5eca2daa"
      url "https://caura.ai/caura/v#{version}/memclaw_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c0a68e59fc598fd2168de51a65cc892b13af19c3d10cc75e58e983c0b61d5018"
      url "https://caura.ai/caura/v#{version}/memclaw_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "901e3c51f1cc9d49666498e40e43315cb448fe11c07bd5f0387be2cd1d949cd2"
      url "https://caura.ai/caura/v#{version}/memclaw_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bcf5308dc00bf3367e74e57bbd7daf0a766ced57f5060a8f11f510fcee7ca870"
      url "https://caura.ai/caura/v#{version}/memclaw_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "caura"
  desc "Local memory broker for AI coding agents"
  homepage "https://caura.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "caura"
  binary "memclaw"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/caura"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/memclaw"] # legacy-name-floor: the staged binary Gatekeeper must unquarantine
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Caura is installed as `caura`. One command wires your agents,
    signs you in, and starts the daemon. The original command name
    remains available too:

      caura setup

    Privacy: by default the broker runs in personal mode. See
    https://caura.ai/legal/privacy for an itemized list of what data
    does and does not leave your machine.
  EOS
end
