# Final manual release. This file WAS generated by GoReleaser, but the
# `homebrew_casks:` section was removed from caura-daemon/.goreleaser.yaml in
# 640c0a7 (2026-09-09) when the Homebrew channel was retired, so nothing
# regenerates it. Pinned by hand to 0.11.0 — the first release whose artifacts
# and binary carry the caura name — so that anyone already installed from this
# tap gets one last upgrade off the old-brand 0.10.5 build before the tap is
# archived. Do not add releases after this one; use the curl installer,
# `npx caurad`, or `uvx caurad`.
cask "caura" do
  version "0.11.0"

  on_macos do
    on_arm do
      sha256 "7e495eadc9974e873f0737ef1e9c44487ae6ef2cbd7e8509b426e0ac069dda5f"
      url "https://caura.ai/caura/v#{version}/caura_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7a00a303c20e0fb9653cef8b2dc57b92ee12c1361a6de0d4bd67742ebf2919fe"
      url "https://caura.ai/caura/v#{version}/caura_#{version}_darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "74074a681cd77755715d94fdc4beb3379dd3540044efbbb50e16934b95742fc3"
      url "https://caura.ai/caura/v#{version}/caura_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "32eeb403aa949c98b91abc9b3aaaecf93b89b0fcc6b15dfc2250d4fb0dcc5ff8"
      url "https://caura.ai/caura/v#{version}/caura_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "caura"
  desc "Local memory broker for AI coding agents"
  homepage "https://caura.ai"

  livecheck do
    skip "Final manual release; channel retired."
  end

  binary "caura"
  # Still shipped: inside the 0.11.0 archive `memclaw` is a symlink to `caura`,
  # kept so existing scripts invoking the old command keep working after the
  # upgrade. # legacy-name-floor: the compatibility command in the archive
  binary "memclaw"

  postflight do
    if OS.mac?
      # Only the real Mach-O needs unquarantining; `memclaw` resolves to it.
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/caura"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Caura is installed as `caura`. One command wires your agents,
    signs you in, and starts the daemon. The original command name
    remains available too:

      caura setup

    This tap is being retired and 0.11.0 is its final release — future
    versions will NOT appear here. Switch to a supported channel when
    convenient:

      curl -fsSL https://caura.ai/install.sh | sh

    or `npx caurad` / `uvx caurad`. See https://caura.ai for the current
    install guide.

    Privacy: by default the broker runs in personal mode. See
    https://caura.ai/legal/privacy for an itemized list of what data
    does and does not leave your machine.
  EOS
end
