# This file was generated by GoReleaser. DO NOT EDIT.
cask "memclaw" do
  version "0.8.2"

  on_macos do
    on_intel do
      sha256 "9f70e6a15583f589d25a99a628712d8381fb2f8c7dadf366f8ae7811d4f0fa9a"
      url "https://memclaw.net/memclaw/v#{version}/memclaw_#{version}_darwin_x86_64.tar.gz",
        verified: "memclaw.net/"
    end
    on_arm do
      sha256 "055da7364d4dc7cd8dec2a9946d7f68fb8c75f2828411d13d7a1a1c1615d5314"
      url "https://memclaw.net/memclaw/v#{version}/memclaw_#{version}_darwin_arm64.tar.gz",
        verified: "memclaw.net/"
    end
  end

  on_linux do
    on_intel do
      sha256 "68738e49ae53fb81bcc337916aeee14fbdb8cc568492d33e40f6414fb419f1f9"
      url "https://memclaw.net/memclaw/v#{version}/memclaw_#{version}_linux_x86_64.tar.gz",
        verified: "memclaw.net/"
    end
    on_arm do
      sha256 "df12ac67bf201f51a544208d424f35b0e1cd759ca710ed3bcf77ee67122b9d39"
      url "https://memclaw.net/memclaw/v#{version}/memclaw_#{version}_linux_arm64.tar.gz",
        verified: "memclaw.net/"
    end
  end

  name "memclaw"
  desc "Local memory broker for AI coding agents"
  homepage "https://memclaw.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memclaw"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/memclaw"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    MemClaw is installed as `memclaw`. One command wires your agents,
    signs you in, and starts the daemon:

      memclaw setup

    Privacy: by default the broker runs in personal mode. See
    https://memclaw.net/privacy for an itemized list of what data
    does and does not leave your machine.
  EOS
end
