# This file was generated by GoReleaser. DO NOT EDIT.
cask "memclaw" do
  version "0.9.1"

  on_macos do
    on_intel do
      sha256 "f371bc1de0fd5f9c6ba7bf2a05ac46a290e3fd85d1dcd71a39c5f4e97b518f39"
      url "https://memclaw.net/memclaw/v#{version}/memclaw_#{version}_darwin_x86_64.tar.gz",
        verified: "memclaw.net/"
    end
    on_arm do
      sha256 "47d7b7b7e28259485f4b687758dfade763744aa88c584fa5dad57f60c4c3ad2d"
      url "https://memclaw.net/memclaw/v#{version}/memclaw_#{version}_darwin_arm64.tar.gz",
        verified: "memclaw.net/"
    end
  end

  on_linux do
    on_intel do
      sha256 "c1685385c6128c8ca10906bd960f1027236efba5d290d125e43704eeaa69daae"
      url "https://memclaw.net/memclaw/v#{version}/memclaw_#{version}_linux_x86_64.tar.gz",
        verified: "memclaw.net/"
    end
    on_arm do
      sha256 "ce6248ce1dfb144e61c758febaac024930533b05096fad50c1b42e5fa76ce0d6"
      url "https://memclaw.net/memclaw/v#{version}/memclaw_#{version}_linux_arm64.tar.gz",
        verified: "memclaw.net/"
    end
  end

  name "memclaw"
  desc "Local memory broker for AI coding agents"
  homepage "https://memclaw.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memclaw"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/memclaw"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    MemClaw is installed as `memclaw`. One command wires your agents,
    signs you in, and starts the daemon:

      memclaw setup

    Privacy: by default the broker runs in personal mode. See
    https://memclaw.net/privacy for an itemized list of what data
    does and does not leave your machine.
  EOS
end
