# This file was generated by GoReleaser. DO NOT EDIT.
cask "memclaw" do
  version "0.8.3"

  on_macos do
    on_intel do
      sha256 "0f8481396e18c66255bcab144cdcb8e2879277afc0a7c0246d3cc1e51968deff"
      url "https://memclaw.net/memclaw/v#{version}/memclaw_#{version}_darwin_x86_64.tar.gz",
        verified: "memclaw.net/"
    end
    on_arm do
      sha256 "7fc2be84dff4cbf3a5e6ef426d86f924742376550c5afca7589bb5b6a9c85e49"
      url "https://memclaw.net/memclaw/v#{version}/memclaw_#{version}_darwin_arm64.tar.gz",
        verified: "memclaw.net/"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec0a918e27c673ab2108b62554ac41dd61dd77c556eba550f0aab8f94972aea5"
      url "https://memclaw.net/memclaw/v#{version}/memclaw_#{version}_linux_x86_64.tar.gz",
        verified: "memclaw.net/"
    end
    on_arm do
      sha256 "1f9a2498e546adcc8f642e0a44b00fd0b996890b808d6650f078c00a8a78b5e9"
      url "https://memclaw.net/memclaw/v#{version}/memclaw_#{version}_linux_arm64.tar.gz",
        verified: "memclaw.net/"
    end
  end

  name "memclaw"
  desc "Local memory broker for AI coding agents"
  homepage "https://memclaw.net"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "memclaw"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/memclaw"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    MemClaw is installed as `memclaw`. One command wires your agents,
    signs you in, and starts the daemon:

      memclaw setup

    Privacy: by default the broker runs in personal mode. See
    https://memclaw.net/privacy for an itemized list of what data
    does and does not leave your machine.
  EOS
end
